plugins {
	id 'java-library'
	id 'eclipse'
	id 'idea'
	id 'net.neoforged.moddev' version '2.0.141'
}

//Set source level
java.toolchain.languageVersion = JavaLanguageVersion.of(25)
println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))

base {
	archivesName = project.properties['file_name']
}

group='com.builtbroken.aiimprovements'

neoForge {
	version = project.properties['neoforge_version']
    validateAccessTransformers = true

	runs {
		configureEach {
			logLevel = org.slf4j.event.Level.DEBUG
			gameDirectory = project.file("run/" + name)
			ideName = "AIImprovements " + ideName.get()
		}

		client {
			client()
		}

		server {
			server()
			programArgument('-nogui')
		}
	}

	mods {
		aiimprovements {
			sourceSet(sourceSets.main)
		}
	}
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes(["Specification-Title": "AI-Improvements",
                    "Specification-Vendor": "Built Broken Modding",
                    "Specification-Version": project.properties['version'],
                    "Implementation-Title": "AI-Improvements",
                    "Implementation-Version": project.properties['version'],
                    "Implementation-Vendor" :"Built Broken Modding"])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
	module {
		downloadSources = true
		downloadJavadoc = true
	}
}