license="MIT License https://github.com/BuiltBrokenModding/AI-Improvements/blob/1.21.11/LICENSE"
issueTrackerURL="https://github.com/BuiltBrokenModding/AI-Improvements/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ai-improvements"
authors="BuiltBrokenModding"

[[mods]]
    modId="aiimprovements"
    version="${file.jarVersion}"
    displayName="AI-Improvements"
    description='''Small adjustments and improvements to AI logic focusing on optimizations for increased server performance'''

[[dependencies.aiimprovements]]
    modId="neoforge"
    type="required"
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aiimprovements]]
    modId="minecraft"
    type="required"
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"